import turtle
turtle.forward(60)
turtle.left(45)
turtle.forward(60)
turtle.left(90)
turtle.forward(60)
turtle.left(45)
turtle.forward(60)
turtle.left(45)
turtle.forward(60)
turtle.left(90)
turtle.forward(60)
